"""emargement electronique

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-29 12:32:41.385888
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0012'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_signature', sa.Column('method', sa.String(length=20), nullable=True), schema='formation')
    op.add_column('attendance_signature', sa.Column('recorded_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('attendance_signature', sa.Column('note', sa.Text(), nullable=True), schema='formation')
    op.add_column('attendance_slot', sa.Column('start_time', sa.Time(), nullable=True), schema='formation')
    op.add_column('attendance_slot', sa.Column('end_time', sa.Time(), nullable=True), schema='formation')
    op.add_column('attendance_slot', sa.Column('trainer_signed_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('attendance_slot', sa.Column('code_hash', sa.String(length=64), nullable=True), schema='formation')
    op.create_unique_constraint(op.f('uq_attendance_slot_code_hash'), 'attendance_slot', ['code_hash'], schema='formation')
    op.add_column('enrollment', sa.Column('sign_token_hash', sa.String(length=64), nullable=True), schema='formation')
    op.create_unique_constraint(op.f('uq_enrollment_sign_token_hash'), 'enrollment', ['sign_token_hash'], schema='formation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_enrollment_sign_token_hash'), 'enrollment', schema='formation', type_='unique')
    op.drop_column('enrollment', 'sign_token_hash', schema='formation')
    op.drop_constraint(op.f('uq_attendance_slot_code_hash'), 'attendance_slot', schema='formation', type_='unique')
    op.drop_column('attendance_slot', 'code_hash', schema='formation')
    op.drop_column('attendance_slot', 'trainer_signed_by', schema='formation')
    op.drop_column('attendance_slot', 'end_time', schema='formation')
    op.drop_column('attendance_slot', 'start_time', schema='formation')
    op.drop_column('attendance_signature', 'note', schema='formation')
    op.drop_column('attendance_signature', 'recorded_by', schema='formation')
    op.drop_column('attendance_signature', 'method', schema='formation')
    # ### end Alembic commands ###
