"""financement

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-29 13:20:42.936093
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0014'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "financement"')
    op.create_table('funding_case',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('cost_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_funding_case_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_case')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_funding_case_enrollment_id')),
    schema='financement'
    )
    op.create_table('funding_source',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('scheme', sa.String(length=30), nullable=False),
    sa.Column('scheme_version', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=True),
    sa.Column('signatory', sa.String(length=200), nullable=True),
    sa.Column('invoice_recipient', sa.String(length=200), nullable=True),
    sa.Column('payer_kind', sa.String(length=20), nullable=False),
    sa.Column('payer_name', sa.String(length=200), nullable=True),
    sa.Column('amount_requested', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_granted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('invoice_ref', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['financement.funding_case.id'], name=op.f('fk_funding_source_case_id_funding_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_source')),
    schema='financement'
    )
    op.create_index(op.f('ix_financement_funding_source_case_id'), 'funding_source', ['case_id'], unique=False, schema='financement')
    op.create_table('funding_step',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=False),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('done_on', sa.Date(), nullable=False),
    sa.Column('portal', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['financement.funding_source.id'], name=op.f('fk_funding_step_source_id_funding_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_step')),
    schema='financement'
    )
    op.create_index(op.f('ix_financement_funding_step_source_id'), 'funding_step', ['source_id'], unique=False, schema='financement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financement_funding_step_source_id'), table_name='funding_step', schema='financement')
    op.drop_table('funding_step', schema='financement')
    op.drop_index(op.f('ix_financement_funding_source_case_id'), table_name='funding_source', schema='financement')
    op.drop_table('funding_source', schema='financement')
    op.drop_table('funding_case', schema='financement')
    op.execute('DROP SCHEMA IF EXISTS "financement"')
    # ### end Alembic commands ###
