"""ressources humaines

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-29 12:54:54.291653
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0013'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE SCHEMA IF NOT EXISTS "rh"')
    op.create_table('staff_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('trainer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['formation.trainer.id'], name=op.f('fk_staff_member_trainer_id_trainer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['iam.user.id'], name=op.f('fk_staff_member_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_member')),
    sa.UniqueConstraint('trainer_id', name=op.f('uq_staff_member_trainer_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_staff_member_user_id')),
    schema='rh'
    )
    op.create_table('staff_absence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['rh.staff_member.id'], name=op.f('fk_staff_absence_staff_id_staff_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_absence')),
    schema='rh'
    )
    op.create_index(op.f('ix_rh_staff_absence_staff_id'), 'staff_absence', ['staff_id'], unique=False, schema='rh')
    op.create_table('staff_contract',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('work_time', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['rh.staff_member.id'], name=op.f('fk_staff_contract_staff_id_staff_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_contract')),
    schema='rh'
    )
    op.create_index(op.f('ix_rh_staff_contract_staff_id'), 'staff_contract', ['staff_id'], unique=False, schema='rh')
    op.add_column('trainer', sa.Column('user_id', sa.String(length=36), nullable=True), schema='formation')
    op.create_unique_constraint(op.f('uq_trainer_user_id'), 'trainer', ['user_id'], schema='formation')
    op.create_foreign_key(op.f('fk_trainer_user_id_user'), 'trainer', 'user', ['user_id'], ['id'], source_schema='formation', referent_schema='iam', ondelete='SET NULL')
    op.add_column('trainer_qualification', sa.Column('kind', sa.String(length=40), server_default='AUTRE', nullable=False), schema='formation')
    op.add_column('trainer_qualification', sa.Column('number', sa.String(length=60), nullable=True), schema='formation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainer_qualification', 'number', schema='formation')
    op.drop_column('trainer_qualification', 'kind', schema='formation')
    op.drop_constraint(op.f('fk_trainer_user_id_user'), 'trainer', schema='formation', type_='foreignkey')
    op.drop_constraint(op.f('uq_trainer_user_id'), 'trainer', schema='formation', type_='unique')
    op.drop_column('trainer', 'user_id', schema='formation')
    op.drop_index(op.f('ix_rh_staff_contract_staff_id'), table_name='staff_contract', schema='rh')
    op.drop_table('staff_contract', schema='rh')
    op.drop_index(op.f('ix_rh_staff_absence_staff_id'), table_name='staff_absence', schema='rh')
    op.drop_table('staff_absence', schema='rh')
    op.drop_table('staff_member', schema='rh')
    op.execute('DROP SCHEMA IF EXISTS "rh"')
    # ### end Alembic commands ###
