"""schema initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 07:24:02.341303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    for schema in ("iam", "formation", "qualite"):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('siret', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    schema='formation'
    )
    op.create_table('organization',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nda_number', sa.String(length=40), nullable=True),
    sa.Column('siret', sa.String(length=20), nullable=True),
    sa.Column('action_categories', sa.JSON(), nullable=False),
    sa.Column('is_new_entrant', sa.Boolean(), nullable=False),
    sa.Column('disability_referent_name', sa.String(length=200), nullable=True),
    sa.Column('disability_referent_email', sa.String(length=200), nullable=True),
    sa.Column('mobility_referent_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    schema='formation'
    )
    op.create_table('outbox_event',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('program_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_event')),
    schema='formation'
    )
    op.create_index(op.f('ix_formation_outbox_event_name'), 'outbox_event', ['name'], unique=False, schema='formation')
    op.create_index(op.f('ix_formation_outbox_event_processed_at'), 'outbox_event', ['processed_at'], unique=False, schema='formation')
    op.create_index(op.f('ix_formation_outbox_event_session_id'), 'outbox_event', ['session_id'], unique=False, schema='formation')
    op.create_table('partner',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('last_contact_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner')),
    schema='formation'
    )
    op.create_table('program',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('action_category', sa.String(length=20), nullable=False),
    sa.Column('is_certifying', sa.Boolean(), nullable=False),
    sa.Column('rncp_code', sa.String(length=40), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('teaching_methods', sa.Text(), nullable=True),
    sa.Column('evaluation_methods', sa.Text(), nullable=True),
    sa.Column('access_delay', sa.String(length=200), nullable=True),
    sa.Column('accessibility_info', sa.Text(), nullable=True),
    sa.Column('certification_alignment', sa.Text(), nullable=True),
    sa.Column('public_info_reviewed_on', sa.Date(), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('satisfaction_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program')),
    sa.UniqueConstraint('code', name=op.f('uq_program_code')),
    schema='formation'
    )
    op.create_table('subcontractor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('siret', sa.String(length=20), nullable=True),
    sa.Column('qualiopi_certified', sa.Boolean(), nullable=False),
    sa.Column('contract_signed_on', sa.Date(), nullable=True),
    sa.Column('last_review_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcontractor')),
    schema='formation'
    )
    op.create_table('trainer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer')),
    schema='formation'
    )
    op.create_table('watch_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('noted_on', sa.Date(), nullable=False),
    sa.Column('exploitation', sa.Text(), nullable=True),
    sa.Column('exploited_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watch_item')),
    schema='formation'
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    schema='iam'
    )
    op.create_table('audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('referential_label', sa.String(length=80), nullable=False),
    sa.Column('planned_on', sa.Date(), nullable=True),
    sa.Column('auditor_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sample_session_ids', sa.JSON(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit')),
    sa.UniqueConstraint('reference', name=op.f('uq_audit_reference')),
    schema='qualite'
    )
    op.create_table('control_result_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('control_key', sa.String(length=120), nullable=False),
    sa.Column('indicator_number', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_control_result_history')),
    schema='qualite'
    )
    op.create_index(op.f('ix_qualite_control_result_history_run_id'), 'control_result_history', ['run_id'], unique=False, schema='qualite')
    op.create_table('evaluation_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('trigger', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation_run')),
    schema='qualite'
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('learner_id', sa.String(length=36), nullable=True),
    sa.Column('trainer_id', sa.String(length=36), nullable=True),
    sa.Column('source_table', sa.String(length=60), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('document_sha256', sa.String(length=64), nullable=True),
    sa.Column('produced_by', sa.String(length=200), nullable=True),
    sa.Column('produced_on', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('form_issues', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('evidence_type', 'source_table', 'source_id', name=op.f('uq_evidence_evidence_type')),
    sa.UniqueConstraint('reference', name=op.f('uq_evidence_reference')),
    schema='qualite'
    )
    op.create_index(op.f('ix_qualite_evidence_enrollment_id'), 'evidence', ['enrollment_id'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_evidence_program_id'), 'evidence', ['program_id'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_evidence_session_id'), 'evidence', ['session_id'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_evidence_status'), 'evidence', ['status'], unique=False, schema='qualite')
    op.create_table('finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('indicator_number', sa.Integer(), nullable=False),
    sa.Column('control_key', sa.String(length=120), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('readiness', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audit_item_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding')),
    sa.UniqueConstraint('key', name=op.f('uq_finding_key')),
    sa.UniqueConstraint('reference', name=op.f('uq_finding_reference')),
    schema='qualite'
    )
    op.create_index(op.f('ix_qualite_finding_indicator_number'), 'finding', ['indicator_number'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_finding_session_id'), 'finding', ['session_id'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_finding_status'), 'finding', ['status'], unique=False, schema='qualite')
    op.create_table('referential_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=400), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('normative_sha256', sa.String(length=64), nullable=False),
    sa.Column('upstream_ref', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referential_version')),
    sa.UniqueConstraint('code', 'version', name=op.f('uq_referential_version_code')),
    schema='qualite'
    )
    op.create_table('sequence',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_sequence')),
    schema='qualite'
    )
    op.create_table('learner',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['formation.company.id'], name=op.f('fk_learner_company_id_company'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learner')),
    schema='formation'
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('trainer_id', sa.String(length=36), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subcontractor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['formation.program.id'], name=op.f('fk_session_program_id_program'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcontractor_id'], ['formation.subcontractor.id'], name=op.f('fk_session_subcontractor_id_subcontractor'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainer_id'], ['formation.trainer.id'], name=op.f('fk_session_trainer_id_trainer'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session')),
    sa.UniqueConstraint('reference', name=op.f('uq_session_reference')),
    schema='formation'
    )
    op.create_table('staff_development_action',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('planned_on', sa.Date(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['formation.trainer.id'], name=op.f('fk_staff_development_action_trainer_id_trainer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_development_action')),
    schema='formation'
    )
    op.create_table('audit_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('indicator_number', sa.Integer(), nullable=False),
    sa.Column('indicator_title', sa.String(length=250), nullable=False),
    sa.Column('engine_readiness', sa.String(length=30), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('judgment', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('judged_by', sa.String(length=200), nullable=True),
    sa.Column('judged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['qualite.audit.id'], name=op.f('fk_audit_item_audit_id_audit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_item')),
    sa.UniqueConstraint('audit_id', 'indicator_number', name=op.f('uq_audit_item_audit_id')),
    schema='qualite'
    )
    op.create_table('capa_action',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('action_plan', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=200), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['qualite.finding.id'], name=op.f('fk_capa_action_finding_id_finding'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_action')),
    sa.UniqueConstraint('reference', name=op.f('uq_capa_action_reference')),
    schema='qualite'
    )
    op.create_index(op.f('ix_qualite_capa_action_finding_id'), 'capa_action', ['finding_id'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_capa_action_status'), 'capa_action', ['status'], unique=False, schema='qualite')
    op.create_table('criterion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['qualite.referential_version.id'], name=op.f('fk_criterion_version_id_referential_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_criterion')),
    sa.UniqueConstraint('version_id', 'number', name=op.f('uq_criterion_version_id')),
    schema='qualite'
    )
    op.create_table('evidence_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['qualite.evidence.id'], name=op.f('fk_evidence_event_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_event')),
    schema='qualite'
    )
    op.create_table('evidence_indicator_link',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('indicator_number', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['qualite.evidence.id'], name=op.f('fk_evidence_indicator_link_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_indicator_link')),
    sa.UniqueConstraint('evidence_id', 'version_id', 'indicator_number', name=op.f('uq_evidence_indicator_link_evidence_id')),
    schema='qualite'
    )
    op.create_table('evidence_validation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('by_user_id', sa.String(length=36), nullable=False),
    sa.Column('by_name', sa.String(length=200), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['qualite.evidence.id'], name=op.f('fk_evidence_validation_evidence_id_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_validation')),
    schema='qualite'
    )
    op.create_table('indicator',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_number', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('ponderation', sa.String(length=40), nullable=False),
    sa.Column('new_entrant_adapted', sa.Boolean(), nullable=False),
    sa.Column('subcontracting', sa.String(length=40), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('editorial_note', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('applicability', sa.JSON(), nullable=False),
    sa.Column('expected_evidence', sa.JSON(), nullable=False),
    sa.Column('human_review', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['qualite.referential_version.id'], name=op.f('fk_indicator_version_id_referential_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator')),
    sa.UniqueConstraint('version_id', 'number', name=op.f('uq_indicator_version_id')),
    schema='qualite'
    )
    op.create_table('attendance_slot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('trainer_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['formation.session.id'], name=op.f('fk_attendance_slot_session_id_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_slot')),
    sa.UniqueConstraint('session_id', 'day', 'period', name=op.f('uq_attendance_slot_session_id')),
    schema='formation'
    )
    op.create_table('complaint',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stakeholder', sa.String(length=20), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acknowledged_on', sa.Date(), nullable=True),
    sa.Column('answered_on', sa.Date(), nullable=True),
    sa.Column('resolved_on', sa.Date(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['formation.session.id'], name=op.f('fk_complaint_session_id_session'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaint')),
    schema='formation'
    )
    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('program_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by', sa.String(length=200), nullable=True),
    sa.Column('indicator_hints', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['formation.program.id'], name=op.f('fk_document_program_id_program'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['formation.session.id'], name=op.f('fk_document_session_id_session'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    schema='formation'
    )
    op.create_table('enrollment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('funding', sa.String(length=60), nullable=True),
    sa.Column('abandoned_on', sa.Date(), nullable=True),
    sa.Column('abandon_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['formation.company.id'], name=op.f('fk_enrollment_company_id_company'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['formation.learner.id'], name=op.f('fk_enrollment_learner_id_learner'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['formation.session.id'], name=op.f('fk_enrollment_session_id_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment')),
    sa.UniqueConstraint('session_id', 'learner_id', name=op.f('uq_enrollment_session_id')),
    schema='formation'
    )
    op.create_table('capa_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capa_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capa_id'], ['qualite.capa_action.id'], name=op.f('fk_capa_event_capa_id_capa_action'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_event')),
    schema='qualite'
    )
    op.create_table('control_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('indicator_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('check', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('guide_section', sa.String(length=80), nullable=True),
    sa.Column('new_entrant_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['qualite.indicator.id'], name=op.f('fk_control_definition_indicator_id_indicator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_control_definition')),
    sa.UniqueConstraint('indicator_id', 'key', name=op.f('uq_control_definition_indicator_id')),
    schema='qualite'
    )
    op.create_table('indicator_text',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('indicator_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['qualite.indicator.id'], name=op.f('fk_indicator_text_indicator_id_indicator'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator_text')),
    schema='qualite'
    )
    op.create_table('agreement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sent_on', sa.Date(), nullable=True),
    sa.Column('signed_on', sa.Date(), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['formation.document.id'], name=op.f('fk_agreement_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_agreement_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agreement')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_agreement_enrollment_id')),
    schema='formation'
    )
    op.create_table('assessment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('assessed_on', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_assessment_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment')),
    schema='formation'
    )
    op.create_table('attendance_signature',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slot_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_attendance_signature_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['formation.attendance_slot.id'], name=op.f('fk_attendance_signature_slot_id_attendance_slot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_signature')),
    sa.UniqueConstraint('slot_id', 'enrollment_id', name=op.f('uq_attendance_signature_slot_id')),
    schema='formation'
    )
    op.create_table('certificate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['formation.document.id'], name=op.f('fk_certificate_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_certificate_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_certificate_enrollment_id')),
    schema='formation'
    )
    op.create_table('convocation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('sent_on', sa.Date(), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['formation.document.id'], name=op.f('fk_convocation_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_convocation_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_convocation')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_convocation_enrollment_id')),
    schema='formation'
    )
    op.create_table('needs_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('adaptation_required', sa.Boolean(), nullable=False),
    sa.Column('adaptation_status', sa.String(length=20), nullable=False),
    sa.Column('adaptation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_needs_analysis_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_needs_analysis')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_needs_analysis_enrollment_id')),
    schema='formation'
    )
    op.create_table('positioning',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('prerequisites_met', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_positioning_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positioning')),
    sa.UniqueConstraint('enrollment_id', name=op.f('uq_positioning_enrollment_id')),
    schema='formation'
    )
    op.create_table('satisfaction_survey',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('sent_on', sa.Date(), nullable=True),
    sa.Column('answered_on', sa.Date(), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['formation.enrollment.id'], name=op.f('fk_satisfaction_survey_enrollment_id_enrollment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['formation.session.id'], name=op.f('fk_satisfaction_survey_session_id_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_satisfaction_survey')),
    schema='formation'
    )
    op.create_table('trainer_qualification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trainer_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('obtained_on', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['formation.document.id'], name=op.f('fk_trainer_qualification_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainer_id'], ['formation.trainer.id'], name=op.f('fk_trainer_qualification_trainer_id_trainer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer_qualification')),
    schema='formation'
    )
    op.create_table('control_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=36), nullable=False),
    sa.Column('control_key', sa.String(length=120), nullable=False),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('indicator_number', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('human_validation_required', sa.Boolean(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['qualite.control_definition.id'], name=op.f('fk_control_result_control_id_control_definition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_control_result')),
    sa.UniqueConstraint('control_id', 'target_type', 'target_id', name=op.f('uq_control_result_control_id')),
    schema='qualite'
    )
    op.create_index(op.f('ix_qualite_control_result_indicator_number'), 'control_result', ['indicator_number'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_control_result_session_id'), 'control_result', ['session_id'], unique=False, schema='qualite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualite_control_result_session_id'), table_name='control_result', schema='qualite')
    op.drop_index(op.f('ix_qualite_control_result_indicator_number'), table_name='control_result', schema='qualite')
    op.drop_table('control_result', schema='qualite')
    op.drop_table('trainer_qualification', schema='formation')
    op.drop_table('satisfaction_survey', schema='formation')
    op.drop_table('positioning', schema='formation')
    op.drop_table('needs_analysis', schema='formation')
    op.drop_table('convocation', schema='formation')
    op.drop_table('certificate', schema='formation')
    op.drop_table('attendance_signature', schema='formation')
    op.drop_table('assessment', schema='formation')
    op.drop_table('agreement', schema='formation')
    op.drop_table('indicator_text', schema='qualite')
    op.drop_table('control_definition', schema='qualite')
    op.drop_table('capa_event', schema='qualite')
    op.drop_table('enrollment', schema='formation')
    op.drop_table('document', schema='formation')
    op.drop_table('complaint', schema='formation')
    op.drop_table('attendance_slot', schema='formation')
    op.drop_table('indicator', schema='qualite')
    op.drop_table('evidence_validation', schema='qualite')
    op.drop_table('evidence_indicator_link', schema='qualite')
    op.drop_table('evidence_event', schema='qualite')
    op.drop_table('criterion', schema='qualite')
    op.drop_index(op.f('ix_qualite_capa_action_status'), table_name='capa_action', schema='qualite')
    op.drop_index(op.f('ix_qualite_capa_action_finding_id'), table_name='capa_action', schema='qualite')
    op.drop_table('capa_action', schema='qualite')
    op.drop_table('audit_item', schema='qualite')
    op.drop_table('staff_development_action', schema='formation')
    op.drop_table('session', schema='formation')
    op.drop_table('learner', schema='formation')
    op.drop_table('sequence', schema='qualite')
    op.drop_table('referential_version', schema='qualite')
    op.drop_index(op.f('ix_qualite_finding_status'), table_name='finding', schema='qualite')
    op.drop_index(op.f('ix_qualite_finding_session_id'), table_name='finding', schema='qualite')
    op.drop_index(op.f('ix_qualite_finding_indicator_number'), table_name='finding', schema='qualite')
    op.drop_table('finding', schema='qualite')
    op.drop_index(op.f('ix_qualite_evidence_status'), table_name='evidence', schema='qualite')
    op.drop_index(op.f('ix_qualite_evidence_session_id'), table_name='evidence', schema='qualite')
    op.drop_index(op.f('ix_qualite_evidence_program_id'), table_name='evidence', schema='qualite')
    op.drop_index(op.f('ix_qualite_evidence_evidence_type'), table_name='evidence', schema='qualite')
    op.drop_index(op.f('ix_qualite_evidence_enrollment_id'), table_name='evidence', schema='qualite')
    op.drop_table('evidence', schema='qualite')
    op.drop_table('evaluation_run', schema='qualite')
    op.drop_index(op.f('ix_qualite_control_result_history_run_id'), table_name='control_result_history', schema='qualite')
    op.drop_table('control_result_history', schema='qualite')
    op.drop_table('audit', schema='qualite')
    op.drop_table('user', schema='iam')
    op.drop_table('watch_item', schema='formation')
    op.drop_table('trainer', schema='formation')
    op.drop_table('subcontractor', schema='formation')
    op.drop_table('program', schema='formation')
    op.drop_table('partner', schema='formation')
    op.drop_index(op.f('ix_formation_outbox_event_session_id'), table_name='outbox_event', schema='formation')
    op.drop_index(op.f('ix_formation_outbox_event_processed_at'), table_name='outbox_event', schema='formation')
    op.drop_index(op.f('ix_formation_outbox_event_name'), table_name='outbox_event', schema='formation')
    op.drop_table('outbox_event', schema='formation')
    op.drop_table('organization', schema='formation')
    op.drop_table('company', schema='formation')
    # ### end Alembic commands ###
    for schema in ("qualite", "formation", "iam"):
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
