"""motif annulation session

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-29 12:19:03.832826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('cancel_reason', sa.Text(), nullable=True), schema='formation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'cancel_reason', schema='formation')
    # ### end Alembic commands ###
