"""cycle de certification et période d'audit

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 10:10:39.933848
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_cycle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('audit_on', sa.Date(), nullable=True),
    sa.Column('certifier', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certification_cycle')),
    schema='qualite'
    )
    op.add_column('audit', sa.Column('period_start', sa.Date(), nullable=True), schema='qualite')
    op.add_column('audit', sa.Column('period_end', sa.Date(), nullable=True), schema='qualite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'period_end', schema='qualite')
    op.drop_column('audit', 'period_start', schema='qualite')
    op.drop_table('certification_cycle', schema='qualite')
    # ### end Alembic commands ###
