"""revue humaine des indicateurs

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-29 10:06:38.180446
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_review',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('indicator_number', sa.Integer(), nullable=False),
    sa.Column('conclusion', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('engine_status', sa.String(length=30), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by', sa.String(length=200), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicator_review')),
    schema='qualite'
    )
    op.create_index(op.f('ix_qualite_indicator_review_indicator_number'), 'indicator_review', ['indicator_number'], unique=False, schema='qualite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualite_indicator_review_indicator_number'), table_name='indicator_review', schema='qualite')
    op.drop_table('indicator_review', schema='qualite')
    # ### end Alembic commands ###
