"""echeancier et signataire de convention

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 09:53:42.622673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_status',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('circuit', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone_status')),
    sa.UniqueConstraint('session_id', 'key', name=op.f('uq_milestone_status_session_id')),
    schema='qualite'
    )
    op.create_index(op.f('ix_qualite_milestone_status_due_on'), 'milestone_status', ['due_on'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_milestone_status_session_id'), 'milestone_status', ['session_id'], unique=False, schema='qualite')
    op.create_index(op.f('ix_qualite_milestone_status_status'), 'milestone_status', ['status'], unique=False, schema='qualite')
    op.add_column('agreement', sa.Column('signed_by', sa.String(length=200), nullable=True), schema='formation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agreement', 'signed_by', schema='formation')
    op.drop_index(op.f('ix_qualite_milestone_status_status'), table_name='milestone_status', schema='qualite')
    op.drop_index(op.f('ix_qualite_milestone_status_session_id'), table_name='milestone_status', schema='qualite')
    op.drop_index(op.f('ix_qualite_milestone_status_due_on'), table_name='milestone_status', schema='qualite')
    op.drop_table('milestone_status', schema='qualite')
    # ### end Alembic commands ###
