"""dossier de pieces

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-29 10:00:24.529438
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('requirement', sa.String(length=60), nullable=False),
    sa.Column('requested_from', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_request')),
    schema='formation'
    )
    op.create_index(op.f('ix_formation_document_request_status'), 'document_request', ['status'], unique=False, schema='formation')
    op.create_index(op.f('ix_formation_document_request_subject_id'), 'document_request', ['subject_id'], unique=False, schema='formation')
    op.add_column('document', sa.Column('requirement', sa.String(length=60), nullable=True), schema='formation')
    op.add_column('document', sa.Column('original_name', sa.String(length=250), nullable=True), schema='formation')
    op.add_column('document', sa.Column('size_bytes', sa.Integer(), nullable=True), schema='formation')
    op.create_index(op.f('ix_formation_document_requirement'), 'document', ['requirement'], unique=False, schema='formation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formation_document_requirement'), table_name='document', schema='formation')
    op.drop_column('document', 'size_bytes', schema='formation')
    op.drop_column('document', 'original_name', schema='formation')
    op.drop_column('document', 'requirement', schema='formation')
    op.drop_index(op.f('ix_formation_document_request_subject_id'), table_name='document_request', schema='formation')
    op.drop_index(op.f('ix_formation_document_request_status'), table_name='document_request', schema='formation')
    op.drop_table('document_request', schema='formation')
    # ### end Alembic commands ###
