"""journal des modifications

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 09:47:15.100344
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('table_name', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_log')),
    schema='formation'
    )
    op.create_index(op.f('ix_formation_change_log_at'), 'change_log', ['at'], unique=False, schema='formation')
    op.create_index(op.f('ix_formation_change_log_entity_id'), 'change_log', ['entity_id'], unique=False, schema='formation')
    op.create_index(op.f('ix_formation_change_log_table_name'), 'change_log', ['table_name'], unique=False, schema='formation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formation_change_log_table_name'), table_name='change_log', schema='formation')
    op.drop_index(op.f('ix_formation_change_log_entity_id'), table_name='change_log', schema='formation')
    op.drop_index(op.f('ix_formation_change_log_at'), table_name='change_log', schema='formation')
    op.drop_table('change_log', schema='formation')
    # ### end Alembic commands ###
