"""alignement modeles

Revision ID: 9a7fd06389a7
Revises: 0001
Create Date: 2026-09-29 19:50:31.578038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a7fd06389a7'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('assessment', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('attendance_signature', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('attendance_slot', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('certificate', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('company', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('complaint', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('convocation', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('document', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('enrollment', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('learner', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('needs_analysis', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('organization', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('partner', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('positioning', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('program', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('satisfaction_survey', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('session', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('staff_development_action', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('subcontractor', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('trainer', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('trainer_qualification', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('watch_item', sa.Column('created_by', sa.String(length=200), nullable=True), schema='formation')
    op.add_column('user', sa.Column('created_by', sa.String(length=200), nullable=True), schema='iam')
    op.add_column('audit', sa.Column('created_by', sa.String(length=200), nullable=True), schema='qualite')
    op.add_column('capa_action', sa.Column('created_by', sa.String(length=200), nullable=True), schema='qualite')
    op.add_column('evidence', sa.Column('created_by', sa.String(length=200), nullable=True), schema='qualite')
    op.add_column('finding', sa.Column('created_by', sa.String(length=200), nullable=True), schema='qualite')
    op.add_column('referential_version', sa.Column('created_by', sa.String(length=200), nullable=True), schema='qualite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referential_version', 'created_by', schema='qualite')
    op.drop_column('finding', 'created_by', schema='qualite')
    op.drop_column('evidence', 'created_by', schema='qualite')
    op.drop_column('capa_action', 'created_by', schema='qualite')
    op.drop_column('audit', 'created_by', schema='qualite')
    op.drop_column('user', 'created_by', schema='iam')
    op.drop_column('watch_item', 'created_by', schema='formation')
    op.drop_column('trainer_qualification', 'created_by', schema='formation')
    op.drop_column('trainer', 'created_by', schema='formation')
    op.drop_column('subcontractor', 'created_by', schema='formation')
    op.drop_column('staff_development_action', 'created_by', schema='formation')
    op.drop_column('session', 'created_by', schema='formation')
    op.drop_column('satisfaction_survey', 'created_by', schema='formation')
    op.drop_column('program', 'created_by', schema='formation')
    op.drop_column('positioning', 'created_by', schema='formation')
    op.drop_column('partner', 'created_by', schema='formation')
    op.drop_column('organization', 'created_by', schema='formation')
    op.drop_column('needs_analysis', 'created_by', schema='formation')
    op.drop_column('learner', 'created_by', schema='formation')
    op.drop_column('enrollment', 'created_by', schema='formation')
    op.drop_column('document', 'created_by', schema='formation')
    op.drop_column('convocation', 'created_by', schema='formation')
    op.drop_column('complaint', 'created_by', schema='formation')
    op.drop_column('company', 'created_by', schema='formation')
    op.drop_column('certificate', 'created_by', schema='formation')
    op.drop_column('attendance_slot', 'created_by', schema='formation')
    op.drop_column('attendance_signature', 'created_by', schema='formation')
    op.drop_column('assessment', 'created_by', schema='formation')
    op.drop_column('agreement', 'created_by', schema='formation')
    # ### end Alembic commands ###
